export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT'
};

export const chatConstants = {
    CHAT_REQUEST: 'CHAT_REQUEST',
    CHAT_CONNECTED: 'CHAT_CONNECTED',
    CHAT_ERROR: 'CHAT_ERROR',
    CHAT_MESSAGE: 'CHAT_MESSAGE',
    CHAT_CLEAR: 'CHAT_CLEAR',
};
